[build]
  publish = "." # Folder utama yang di-upload

[build.processing]
  skip_processing = false # Biar Netlify ngatur optimasi otomatis

[build.processing.html]
  pretty_urls = true # Biar link-nya cakep (gak ada .html)

[build.processing.css]
  bundle = true 
  minify = true # Biar CSS-nya enteng

[build.processing.js]
  bundle = true
  minify = true # Biar JS-nya cepet

[build.processing.images]
  compress = true # Gambar dikecilin biar gak berat
